# Generated by Django 3.1 on 2021-02-25 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.CharField(blank=True, max_length=350)),
                ('profile_avatar', models.ImageField(blank=True, upload_to='AvatorPicture/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='postgram/')),
                ('image_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_image', to=settings.AUTH_USER_MODEL)),
                ('image_likes', models.ManyToManyField(blank=True, default=False, related_name='likes', to='list.Profile')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_image', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_post', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_comment', to='list.profile')),
                ('comment_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='list.postimage')),
            ],
        ),
    ]
