# Generated by Django 3.1 on 2021-02-25 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20210225_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'ordering': ('created_at',)},
        ),
    ]
