# Generated by Django 3.1 on 2021-02-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20210225_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image_description',
            field=models.CharField(max_length=1000),
        ),
    ]
