# Generated by Django 3.1 on 2021-02-25 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_auto_20210225_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='image_likes',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_image', to='list.profile'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_image', to='list.profile'),
        ),
    ]
