# Generated by Django 3.1 on 2021-02-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20210225_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image_description',
            field=models.TextField(blank=True),
        ),
    ]
